### ISSUE TITLE
Be more resilient to upstream inconsistencies

### ISSUE THREAD

**Issue by symroe** [DemocracyClub/aggregator-api#211]
There are some times when WDIV and WCIVF will have different lists of ballots.

This might be due to an actual problem with one upstream, or just a lag in syncing.

If this happens, we get a 500 along the lines of:

```Traceback (most recent call last):
  File "/home/symroe/Projects/democracyclub/aggregator_api/aggregator/apps/api/v1/views.py", line 41, in get_response
    stitcher = Stitcher(wdiv, wcivf, request)
  File "/home/symroe/Projects/democracyclub/aggregator_api/aggregator/apps/api/v1/stitcher.py", line 99, in __init__
    self.validate()
  File "/home/symroe/Projects/democracyclub/aggregator_api/aggregator/apps/api/v1/stitcher.py", line 105, in validate
    f'Could not find expected ballot {ballot["ballot_paper_id"]}'
api.v1.stitcher.StitcherValidationError: Could not find expected ballot local.gloucestershire.stroud-central.2021-05-06```

This sort of problem can be hard to spot, as it might only affect a small subset of all postcodes.

**Comment by symroe** [comment]
We no longer get a 500, but we do get a sentry alert raised. Considering this closed.
